export const cartActionTypes = {
    TOGGLE_CART_HIDDEN : "TOGGLE_CART_HIDDEN",
    ADD_ITEMS : "ADD_ITEMS",
    REMOVE_CART_ITEM : "REMOVE_CART_ITEM",
    CLEAR_ITEMS_FROM_CART : "CLEAR_ITEMS_FROM_CART",
    CLEAR_CART : "CLEAR_CART"
}