export const userActionTypes = {
    GOOGLE_SIGNIN_START : "GOOGLE_SIGNIN_START",
    EMAIL_SIGNIN_START : "EMAIL_SIGNIN_START",
    SIGNIN_SUCCESS : "SIGNIN_SUCCESS",
    CHECK_USER_SESSION : "CHECK_USER_SESSION",
    SIGNOUT_START : "SIGNOUT_START",
    SIGNOUT_SUCCESS : "SIGNOUT_SUCCESS",
    SIGNIN_SIGNOUT_FAILURE : "SIGNIN_SIGNOUT_FAILURE",
    SIGN_UP_START : "SIGN_UP_START",
    SIGN_UP_SUCCESS : "SIGN_UP_SUCCESS",
    SIGN_UP_FAILURE : "SIGN_UP_FAILURE",
}